### ISSUE TITLE
App automatically close.

### ISSUE THREAD

**Issue by kirael** [lincanbin/Android-Carbon-Forum#8]
I compile the source with no error but when i open the app its automatically close.

**Comment by kirael** [comment]
04-17 16:38:38.192 3216-3216/? E/AndroidRuntime: in writeCrashedAppName, pkgName :com.lincanbin.carbonforum
04-17 16:38:38.192 3216-3216/? D/AndroidRuntime: file written successfully with content: com.lincanbin.carbonforum StringBuffer : ;com.lincanbin.carbonforum
04-17 16:38:38.202 3216-3216/? I/Process: Sending signal. PID: 3216 SIG: 9
04-17 16:38:38.202 3216-3216/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.lincanbin.carbonforum, PID: 3216
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lincanbin.carbonforum/com.pepeng.malupet.IndexActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                     at com.pepeng.malupet.IndexActivity.onCreate(IndexActivity.java:71)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                     at com.pepeng.malupet.IndexActivity.onCreate(IndexActivity.java:71) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_add_24dp.xml from drawable resource ID #0x7f02004e
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2096)
                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                     at android.widget.ImageView.<init>(ImageView.java:129)
                                                     at android.widget.ImageButton.<init>(ImageButton.java:87)
                                                     at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57)
                                                     at android.support.design.widget.VisibilityAwareImageButton.<init>(VisibilityAwareImageButton.java:37)
                                                     at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:109)
                                                     at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:105)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                     at com.pepeng.malupet.IndexActivity.onCreate(IndexActivity.java:71) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2092)
                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                     at android.widget.ImageView.<init>(ImageView.java:129) 
                                                     at android.widget.ImageButton.<init>(ImageButton.java:87) 
                                                     at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57) 
                                                     at android.support.design.widget.VisibilityAwareImageButton.<init>(VisibilityAwareImageButton.java:37) 
                                                     at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:109) 
                                                     at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:105) 
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                     at com.pepeng.malupet.IndexActivity.onCreate(IndexActivity.java:71) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
04-17 16:38:38.202 1732-2115/system_process I/ActivityManager: Process com.lincanbin.carbonforum (pid 3216) has died.

**Comment by lincanbin** [comment]
http://android-developers.blogspot.sg/2016/02/android-support-library-232.html

Try this or use Gradle Plugin 2.0+.

**Comment by kirael** [comment]
how do i use that. sorry im new in android programming

**Comment by kirael** [comment]
and i try to use 5.0.1 the release and then same problem occur

**Comment by lincanbin** [comment]
your android studio version?

**Comment by kirael** [comment]
my android stud version is 2.0

**Comment by lincanbin** [comment]
https://github.com/lincanbin/Android-Carbon-Forum/blob/master/build.gradle#L8
Check here.
